[package]
name = "test-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Dependencies needed for generated contract wrappers

ink-wrapper-types = { path = "../ink-wrapper-types" }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }

# aleph_client version equal to the one used in ink-wrapper-types

aleph_client = { git = "https://github.com/Cardinal-Cryptography/aleph-node.git", rev = "0bf23c86fd3ada6a72928b2e019b8eba46430368" }

# Other dependencies

ink_primitives = "4.0.0-beta.1"
async-trait = "0.1.64"
anyhow = "1.0.69"
tokio = "1.25.0"
sp-core = "16.0.0"
rand = "0.8.4"
