---
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run all checks
        run: make all-dockerized

  publish:
      needs: [ build-and-test ]
      runs-on: ubuntu-latest
      if: github.repository == 'Cardinal-Cryptography/ink-wrapper' && startsWith(github.ref, 'refs/heads/') && github.ref_name == 'main'
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      steps:
        - uses: actions/checkout@v4
        - uses: Cardinal-Cryptography/aleph-node/.github/actions/install-rust-toolchain@5eda3cd85e7e3aec3f2db7a26631c65d52c4b9ea
        - uses: './.github/actions/publish-if-newer'
          with:
            package: ink-wrapper-types
        - uses: './.github/actions/publish-if-newer'
          with:
            package: ink-wrapper