---
name: Publish to crates
on:
  push:
    branches: [ main ]
jobs:
  publish:
    needs: [ build-and-test ]
    runs-on: ubuntu-latest
    if: github.repository == 'Cardinal-Cryptography/ink-wrapper' && startsWith(github.ref, 'refs/heads/') && github.ref_name == 'main'
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: Cardinal-Cryptography/aleph-node/.github/actions/install-rust-toolchain@5eda3cd85e7e3aec3f2db7a26631c65d52c4b9ea
      - uses: './.github/actions/publish-if-newer'
        with:
          package: ink-wrapper-types
      - uses: './.github/actions/publish-if-newer'
        with:
          package: ink-wrapper
